import { Tab } from '@headlessui/react';
import Head from 'next/head';
import Cart from '../components/Cart';
import { getSession } from 'next-auth/react';
import Hero from '../components/Hero';
import Product from '../components/Product';
import { fetchCategories } from '../lib/fetchCategories';
import { fetchProducts } from '../lib/fetchProducts';

export default function Home({ categories, products }) {
  const showProducts = (cat) => {
    return products
      .filter((product) => product.category?._ref === categories[cat]._id)
      .map((product) => <Product key={product._id} product={product} />);
  };

  return (
    <div>
      <Head>
        <title>Apple Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* <Header /> */}
      <Cart />
      <main className='relative h-[200vh] bg-[#e9eced]'>
        <Hero />
      </main>
      <section className='relative z-40 -mt-[100vh] min-h-screen bg-[#1b1b1b]'>
        <div className='space-y-10 py-16'>
          <h1 className='text-center text-4xl font-medium tracking-wide text-white md:text-5xl'>
            New Promos
          </h1>

          {/* Headless UI code here for tabbed panels */}
          <Tab.Group>
            <Tab.List className='flex justify-center'>
              {categories.map((category) => (
                <Tab
                  key={category._id}
                  id={category._id}
                  className={({ selected }) =>
                    `whitespace-nowrap rounded-t-lg py-3 px-5 text-sm font-light outline-none md:py-4 md:px-6 md:text-base ${
                      selected
                        ? 'borderGradient bg-[#35383C] text-white'
                        : 'border-b-2 border-[#35383C] text-[#747474]'
                    }`
                  }
                >
                  {category.title}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className='mx-auto max-w-fit pt-10 pb-24 sm:px-4'>
              <Tab.Panel className='tabPanel'>{showProducts(0)}</Tab.Panel>
              <Tab.Panel className='tabPanel'>{showProducts(1)}</Tab.Panel>
              <Tab.Panel className='tabPanel'>{showProducts(2)}</Tab.Panel>
              <Tab.Panel className='tabPanel'>{showProducts(3)}</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </section>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const categories = await fetchCategories();
  const products = await fetchProducts();

  const session = await getSession(context);

  return {
    props: {
      categories,
      products,
      session,
    },
  };
};
